# Generated by Django 4.2.30 on 2026-04-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(check=models.Q(('amount_paise__gt', 0)), name='ledgerentry_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'debit')), fields=('payout',), name='unique_debit_per_payout'),
        ),
    ]
