# Generated by Django 4.2.30 on 2026-04-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.CheckConstraint(check=models.Q(('amount_paise__gt', 0)), name='payout_positive_amount'),
        ),
    ]
